language: go
go: 
 - 1.13.x

before_install:
    - sudo pip install --user codecov

install:
- go mod vendor

script:
 - go test -v -race -coverprofile=coverage.txt

after_success:
    - bash <(curl -s https://codecov.io/bash)
